version: "3.9"

services:
  dashy:
    image: lissy93/dashy:latest

    restart: always

    environment:
      - NODE_ENV=production
      
    volumes:
      - ./dashy-conf.yml:/app/public/conf.yml

    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    external:
      name: ${NETWORK_NAME}
