version: "3.9"

services:
  dashy:
    image: lissy93/dashy:latest
    
    container_name: dashy

    restart: always
    
    # Remove the exposed ports if using network bridge with reverse proxy
    ports:
      - 4000:80

    environment:
      - NODE_ENV=production
      
    volumes:
      - ./dashy-conf.yml:/app/public/conf.yml

    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Overrides the default network of the compose stack, use this for exposing dashy indirectly through a reverse proxy

# networks:
#   default:
#     name: ${NETWORK_NAME}
#     external: true

